# Generated by Django 3.2.7 on 2021-10-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_tbl',
            name='phoneno',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_tbl',
            name='phoneno',
            field=models.CharField(default='', max_length=50),
        ),
    ]
