# Generated by Django 3.2.7 on 2021-10-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0003_pets_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets_tbl',
            name='file',
            field=models.FileField(upload_to='pets'),
        ),
    ]
