# Generated by Django 3.2.7 on 2021-11-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_alter_pets_tbl_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets_tbl',
            name='quantity',
            field=models.CharField(default='10', max_length=50),
        ),
    ]
