# Generated by Django 3.2.7 on 2021-11-26 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0005_pets_tbl_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='', max_length=100)),
                ('total', models.CharField(default='', max_length=100)),
                ('unitprice', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('pid', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='petapp.pets_tbl')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.user_tbl')),
            ],
        ),
    ]
