# Generated by Django 3.2.7 on 2021-11-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_cart_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_signup_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=50)),
                ('lastname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('gender', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('hpassword', models.TextField(default='')),
            ],
        ),
    ]
