# Generated by Django 3.2.7 on 2021-11-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_admin_signup_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets_tbl',
            name='status',
            field=models.CharField(default='approved', max_length=50),
        ),
    ]
