# Generated by Django 3.2.7 on 2021-11-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0008_pets_tbl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_tbl',
            name='status',
            field=models.CharField(default='approved', max_length=50),
        ),
    ]
