# Generated by Django 3.2.7 on 2021-11-30 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0009_user_tbl_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='paid', max_length=50)),
                ('date', models.CharField(default='', max_length=50)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petapp.user_tbl')),
            ],
        ),
    ]
